apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-api
  namespace: rest
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: rest-api
        serviceName: rest-api
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: rest-api
        image: index.docker.io/mateuszdyminski/rest:latest
        ports:
          - containerPort: 8080
        resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 10Mi
              cpu: 20m